application:
  subdomain: httpbun
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://httpbun:80/
services:
  httpbun:
    # upstream: sharat87/httpbun:latest
    image: sharat87/httpbun:latest
